---
- name : Start Looker
  msg: "start initiated by Ansible after file update"
  service: 
    name: Looker
    state: started
    enabled: yes
  register: myserviceDetails
  until: myserviceDetails.status.ActiveState == "active"
  retries: 10
  delay: 20  