---
  - name: Move files
    command: mv /home/looker/looker/looker.jar /backup/looker_{{ansible_date_time.date}}.jar

  - name: Move files
    command: mv /home/looker/looker/looker-dependencies.jar /var/www/html/looker-dependencies_{{ansible_date_time.date}}.jar  

  - name: list directory
    shell: | 
      echo -e "\n Present working directory is" `pwd`
          
      echo -e "\n Directory listing"
      ls /home/looker/looker/
    
    args:
       chdir: "/home/looker/looker/"
    register: filemove
    tags: filemove 
  
  - name: Print version
    debug: 
      msg: "Ansible move: {{ filemove }}"