---
  - name: Move files
    command: mv /home/ubuntu/*.txt /tmp

  - name: list directory
    shell: | 
      echo -e "\n Present working directory is" `pwd`
          
      echo -e "\nDirectory listing"
      ls /var/www/html/
    
    args:
       chdir: "/home/ubuntu/"
    register: filemove
    tags: filemove 
  
  - name: Print version
    debug: 
      msg: "Ansible move: {{ filemove }}"