---
  - name: Restart Apache
    shell: |
      echo -e "\n Stopping the looker service and login with looker user"
      sudo systemctl stop apache2

    args:
       chdir: "/home/ubuntu/"
    register: fileout
    tags: fileout 
  
  - name: Print version
    debug: 
      msg: "Ansible output: {{ fileout }}"
