---

- name: Download looker.jar file from gcp looker_bucket
  gc_storage:
    bucket: looker_bucket
    object: looker.jar
    dest: /home/looker/looker/
    mode: get

- name: Download looker-dependencies.jar file from gcp looker_bucket
  gc_storage:
    bucket: looker_bucket
    object: looker-dependencies.jar
    dest: /home/looker/looker/
    mode: get    

- name: list directory
  shell: | 
    echo -e "\n Directory listing"
    ls /home/looker/looker/
    
  notify:
      - Start Looker  

- name: Sleep for 60 seconds and timeout
  wait_for:
    delay: 120
    timeout: 0      
      
  args:
     chdir: "/home/looker/looker/"
  register: filecopy
  tags: filecopy 
  
- name: Print version
  debug: 
    msg: "Ansible copy: {{ filecopy }}"    