---
  - name: Copu files from gcp bucket
    copy: 
      src: /home/ubuntu/test235.txt
      dest: /var/www/html
      remote_src: yes

  - name: list directory
    shell: | 
      echo -e "\n Present working directory is" `pwd`
          
      echo -e "\nDirectory listing"
      ls /var/www/html/
    
    args:
       chdir: "/home/ubuntu/"
    register: filecopy
    tags: filecopy 
  
  - name: Print version
    debug: 
      msg: "Ansible copy: {{ filecopy }}"